### PR TITLE
Add Legal Notice

### PR DESCRIPTION
**Pull request by tiwanari**
This PR introduces the Legal Notice of our apps.

## Output
This PR provides the following page;
screenshot_20161202-151310

## How to update it
1. modify `app/src/main/assets/legal_notice_template.md`

2. use [pandoc](https://www.google.co.jp/search?q=pandoc&oq=pandoc&aqs=chrome..69i57j69i65l2j0l3.890j0j1&sourceid=chrome&ie=UTF-8) to convert the above markdown to a html.

```
pandoc legal_notice_template.md
```

Then, you'll get the converted result.

3. copy the result and paste it into the `article` element of `app/src/main/assets/legal_notice.html`

## NOTE
I used [sindresorhus/github-markdown-css: The minimal amount of CSS to replicate the GitHub Markdown style]( https://goo.gl/kZ7YZY ) for the pages' css.

## Discussion
Please feel free to leave comments on the contents of the legal notice.

### CODE REVIEW

**Comment by tiwanari** [comment]
I added a small change; merged duplicated xmls into one.

**Review by mandaiy — COMMENTED** [review]
Who wrote this?
Is it effective in terms of legal document?

**Comment by tiwanari** [comment]
I checked some notices of some applications and terms online and wrote it. I can guess what you want me to do but it's time and money consuming.

**Review by mandaiy — APPROVED** [review]

**Comment by tiwanari** [comment]
Thank you for your review. I will merge this :)

**Pull request merged**
